language:  python
services:
  - docker
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=cov
matrix:
  allow_failures:
    - env: TOXENV=cov
install: 
   - pip install tox
script:
   - tox
after_script:
  - if [ $TOXENV == "cov" ];
    then
      pip install coveralls;
      coveralls;
    else
      echo 'Start Integration-Tests in Docker:'
      python tests/integration_test_runner.py `echo ${PWD}` $TOXENV dpkg pacman rpm
    fi