language:  python
services:
  - docker
matrix:
  allow_failures:
    - env: TOXENV=cov
  include:
    - python: 2.7
      env:
      - TOXENV=py27
  include:
    - python: 3.3
      env:
      - TOXENV=py33
  include:
    - python: 3.4
      env:
      - TOXENV=py34
  include:
    - python: 3.5
      env:
      - TOXENV=py35
  include:
    - python: 3.6
      env:
      - TOXENV=py36
  include:
    - python: pypy
      env:
      - TOXENV=pypy
install:
   - pip install tox
script:
   - tox
after_script:
  - if [ $TOXENV == "cov" ];
    then
      pip install coveralls;
      coveralls;
    else
      echo 'Start Integration-Tests in Docker:';
      python tests/integration_test_runner.py `echo ${PWD}` $TOXENV dpkg pacman rpm;
    fi