language:  python
services:
  - docker
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=cov
matrix:
  allow_failures:
    - env: TOXENV=cov
  # python3.6 compatibility See: https://github.com/travis-ci/travis-ci/issues/4794 (Comment BanzaiMan)
  include:
    - python: 3.6
      env:
      - TOXENV=py36
install: 
   - pip install tox
script:
   - tox
after_script:
  - if [ $TOXENV == "cov" ];
    then
      pip install coveralls;
      coveralls;
    else
      echo 'Start Integration-Tests in Docker:';
      python tests/integration_test_runner.py `echo ${PWD}` $TOXENV dpkg pacman rpm;
    fi